ctgsize=/netscratch/dep_mercier/grp_schneeberger/projects/Potato_single_cells/reference_manish_assembled_haplotye_aware/hifiasm_assembly_polish_and_select_v2/s0_select_long_contigs_v2/exclude_subset_5/HiFiasm_ref_pilon_6366long_ctgs_selected.ctgsizes

fasta=/netscratch/dep_mercier/grp_schneeberger/projects/Potato_single_cells/reference_manish_assembled_haplotye_aware/hifiasm_assembly_polish_and_select_v2/s0_select_long_contigs_v2/exclude_subset_5/HiFiasm_ref_pilon_6366long_ctgs_selected.fasta
marker_grouping=/netscratch/dep_mercier/grp_schneeberger/projects/Potato_single_cells/reference_manish_assembled_haplotye_aware/hifiasm_assembly_polish_and_select_v2/s5_selected_long_contigs_sc_read_coverage_genotype_v2/s4_step5_gamete_binning_selected717_cor0.55_ncor-0.25_minHap100000_ncorminus_recalc_tmp_integrating_all_ctg_markers_to_LGs/s4p6_refine_grouping_final_window_markers_sorted.txt

extract_fasta_with_gbMarker_grouping ${fasta} ${marker_grouping} 

