debug_noisy:
	g++ get_vars_within_alignments.cpp split_string.cpp -O3 -o get_vars_within_alignments
	cp get_vars_within_alignments ../dev_bin
#	cp get_vars_within_alignments /Users/sun/Softwares/dev_bin
